version: "3.7"


# services:
#   docs:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: dev
#     ports:
#       - 8000:8000
#     volumes:
#       - ./:/app

services:
  lottery_web_api:
    container_name: lottery_web_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7001:8080
    environment:
      - NODE_ENV=development


